switch:
  - platform: mqtt
    name: "Doorbell"
    state_topic: "home/doorbell"
    command_topic: "home/doorbell/set"

light:
  - platform: mqtt
    schema: json
    name: "LED Strip"
    state_topic: "home/ledstrip1"
    command_topic: "home/ledstrip1/set"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle  
    brightness: true
    # flash: true
    rgb: true
    optimistic: false
    qos: 0

input_number:
  led_animation_speed:
    name: LED Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

automation: 
  - alias: "LED Animation Speed"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_number.led_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "home/ledstrip1/set"
          payload: '{"transition":{{ trigger.to_state.state | int }}}'
