switch:
  - platform: mqtt
    name: "Doorbell"
    state_topic: "home/doorbell"
    command_topic: "home/doorbell/set"
  - platform: mqtt
    name: "OfficeDoor"
    state_topic: "office/door1"
    command_topic: "office/door1/set"
  - platform: mqtt
    name: "Office Switch"
    state_topic: "office/switch-x1"
    command_topic: "office/switch-x1/set"
  - platform: mqtt
    name: "Home Switch 1"
    state_topic: "home/switch_a_d1"
    command_topic: "home/switch_a_d1/set"
  - platform: mqtt
    name: "Home Switch 2"
    state_topic: "home/switch_a_d2"
    command_topic: "home/switch_a_d2/set"
    
light:
  - platform: mqtt
    schema: json
    name: "LEDS A1"
    # entity_id: ledstrip_group1_m1
    state_topic: "home/ledstrip_group1_m1"
    command_topic: "home/ledstrip_group1_m1/set"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle  
    brightness: true
    # flash: true
    rgb: true
    optimistic: false
    qos: 0
  - platform: mqtt
    schema: json
    name: "LEDS A2"
    # entity_id: ledstrip_group1_m2
    state_topic: "home/ledstrip_group1_m2"
    command_topic: "home/ledstrip_group1_m2/set"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle  
    brightness: true
    # flash: true
    rgb: true
    optimistic: false
    qos: 0
  - platform: mqtt
    schema: json
    name: "LEDS A3"
    # entity_id: ledstrip_group1_m3
    state_topic: "home/ledstrip_group1_m3"
    command_topic: "home/ledstrip_group1_m3/set"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle  
    brightness: true
    # flash: true
    rgb: true
    optimistic: false
    qos: 0
  - platform: mqtt
    schema: json
    name: "LEDS A4"
    # entity_id: ledstrip_group1_m4
    state_topic: "home/ledstrip_group1_m4"
    command_topic: "home/ledstrip_group1_m4/set"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle  
    brightness: true
    # flash: true
    rgb: true
    optimistic: false
    qos: 0
  - platform: mqtt
    schema: json
    name: "LEDS A5"
    state_topic: "home/ledstrip1"
    command_topic: "home/ledstrip1/set"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle  
    brightness: true
    rgb: true
    optimistic: false
    qos: 0
input_number:
  led_animation_speed:
    name: LED Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10
  led_animation_speed_group:
    name: "LED动画速度"
    initial: 50
    min: 1
    max: 150
    step: 10

automation: 
  - alias: "LED Animation Speed"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_number.led_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "home/ledstrip1/set"
          payload: '{"transition":{{ trigger.to_state.state | int }}}'

  - alias: "LED A动画速度"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_number.led_animation_speed_group
    action:
      - service: mqtt.publish
        data_template:
          topic: "home/ledstrip_group1_m1/set"
          payload: '{"transition":{{ trigger.to_state.state | int }}}'
      - service: mqtt.publish
        data_template:
          topic: "home/ledstrip_group1_m2/set"
          payload: '{"transition":{{ trigger.to_state.state | int }}}'
      - service: mqtt.publish
        data_template:
          topic: "home/ledstrip_group1_m3/set"
          payload: '{"transition":{{ trigger.to_state.state | int }}}'
      - service: mqtt.publish
        data_template:
          topic: "home/ledstrip_group1_m4/set"
          payload: '{"transition":{{ trigger.to_state.state | int }}}'
      - service: mqtt.publish
        data_template:
          topic: "home/ledstrip_group1_m5/set"
          payload: '{"transition":{{ trigger.to_state.state | int }}}'
          
  # - alias: "嘉禾音效开场"
  #   initial_state: True
  #   trigger:
  #     - platform: time
  #       # Military time format. This trigger will fire at 3:32 PM
  #       at: '16:20:00'
  #   action:
  #     - service: script.jiahe_script