light:
  - platform: mqtt
    schema: json
    name: "LED G1"
    state_topic: "home/leds_g_d1"
    command_topic: "home/leds_g_d1/set"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - stepbystep_10_300
      - stepbystep_10_500
      - stepbystep_10_800
      - stepbystep_20_300
      - stepbystep_20_500
      - stepbystep_20_800
    brightness: true
    rgb: true
    optimistic: false
    qos: 0


script:
  change_g1_bright:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.led_g1
          brightness: 50

automation:
  - id: change_g1_bright
    alias: '修改g1亮度'
    trigger:
      platform: state
      entity_id: switch.wall_switch_right_158d00024c157a
      from: 'off'
      to: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.led_g1
          brightness: 50

group:  
  leds_g:
    name: G1 ( Multiple V4固件 )
    entities:
    - light.led_g1
    - script.change_g1_bright
    - automation.change_g1_bright